[output]
deny = ["unmaintained", "unsound", "yanked"]
quiet = false

[advisories]
ignore = [
    # Ignore Windows-only advisory for atty
    "RUSTSEC-2021-0145",
    # Ignore advisory for mach (only used by psutil on macOS)
    "RUSTSEC-2020-0168",
    # pqcrypto-kyber is our Kyber implementation
    "RUSTSEC-2024-0381",
    # Ignore until fixed upstream (see https://github.com/aws/aws-lc-rs/issues/722)
    "RUSTSEC-2024-0436",
    # Ignore until fixed upstream (see https://github.com/apache/arrow-rs/issues/7264)
    "RUSTSEC-2025-0014",
]
