#
# Copyright 2019-2021 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "calling_common"
version = "0.0.0"
authors = ["Calling Team <callingteam@signal.org>"]
edition = "2021"
description = "Common calling library."
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.86"
base64 = "0.22.1"
env_logger = "0.11.3"
log = "0.4.22"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
sha2 = "0.10.8"
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0.62"

[dev-dependencies]
hex = { version = "0.4.3", features = ["serde"] }
hex-literal = "0.4.1"
